# This file controls the AWS CodeBuild
version: 0.2
phases:
  pre_build:
    commands:
    - echo "The program entered the pre-build phase today"
  build:
    commands:
    - echo "Entered build phase today"
    - mvn clean prepare-package war:exploded
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mv target/deploy .
artifacts:
  files:
    - deploy/**/*
